frontend:
    image: frontend
    links:
        - level0
        - level1
        - level2
        - level3
        - level4
        - level5
        - level6
        - level7
level0:
    image: level0
    environment:
        PASSWORD_LEVEL1: reallyrandom
level1:
    image: level1
    environment:
        PASSWORD_LEVEL2: someotherpassword
level2:
    image: level2
level3:
    image: level3
level4:
    image: level4
level5:
    image: level5
    dns: 192.168.168.192
level6:
    image: level6
level7:
    image: level7

